name: Deploy Worker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun runtime
        # Uses the official action to install Bun
        uses: oven-sh/setup-bun@v2 
        with:
          # Optionally specify a version: bun-version: 1.x.x
          bun-version: latest

      - name: Install dependencies with Bun
        run: bun install

      - name: Deploy Worker with Wrangler Action
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --minify
        env:
          WEBHOOK_AUTH_CLIENT_KEY: ${{ secrets.WEBHOOK_AUTH_CLIENT_KEY }}